version: "3.8"

services:
  node_app:
    build: ./
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "8081:8081"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - node_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
