version: "3.8"

services:
  node_app:
    build: ./
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "8081:8081"

  nginx:
    image: nginx:latest
    # OR if you're still using a custom Dockerfile, replace with:
    # build: ./nginx
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - node_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 1. Mount the live cert folder (read-only):
      - /etc/letsencrypt/live/api.quizabble.com:/etc/letsencrypt/live/api.quizabble.com:ro

      # 2. Mount the Let’s Encrypt `options-ssl-nginx.conf` file if you want it:
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro

      # 3. If you still want the ACME challenge folder (optional):
      - ./nginx:/etc/nginx/templates
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - /etc/letsencrypt:/etc/letsencrypt:ro

    environment:
      - ENV=production
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
